# Generated by Django 4.2.22 on 2025-08-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPergunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição ou uma explicação sobre a categoria')),
                ('is_active', models.BooleanField(default=True, help_text='Se ativa, pode ser utilizada.', verbose_name='Ativo')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash')),
            ],
            options={
                'ordering': ['titulo'],
                'unique_together': {('titulo',)},
            },
        ),
    ]
