# Generated by Django 4.2.22 on 2025-08-16 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repadel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriapergunta',
            options={'ordering': ['nome']},
        ),
        migrations.RenameField(
            model_name='categoriapergunta',
            old_name='titulo',
            new_name='nome',
        ),
        migrations.AlterUniqueTogether(
            name='categoriapergunta',
            unique_together={('nome',)},
        ),
    ]
