# Generated by Django 4.2.22 on 2025-08-16 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repadel', '0002_alter_categoriapergunta_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriapergunta',
            options={'ordering': ['-is_active', 'nome']},
        ),
    ]
