# Generated by Django 4.2.22 on 2025-08-17 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repadel', '0003_alter_categoriapergunta_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('texto', 'Resposta Aberta (texto)'), ('numerica', 'Resposta Numérica'), ('multipla', 'Múltipla Escolha')], default='multipla', max_length=20)),
                ('obrigatoria', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True, help_text='Se ativa, pode ser utilizada.', verbose_name='Ativo')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='categoria', to='repadel.categoriapergunta')),
            ],
            options={
                'verbose_name': 'pergunta',
                'verbose_name_plural': 'perguntas',
                'ordering': ['-is_active', 'categoria', 'texto'],
                'unique_together': {('categoria', 'texto')},
            },
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveSmallIntegerField()),
                ('texto', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pergunta', to='repadel.pergunta')),
            ],
            options={
                'verbose_name': 'alternativa',
                'verbose_name_plural': 'alternativas',
                'ordering': ['codigo'],
                'unique_together': {('pergunta', 'codigo')},
            },
        ),
    ]
