# Generated by Django 4.2.22 on 2025-08-17 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repadel', '0004_pergunta_alternativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativa',
            name='codigo',
            field=models.PositiveSmallIntegerField(verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='alternativa',
            name='pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pergunta', to='repadel.pergunta', verbose_name='Pergunta associada'),
        ),
        migrations.AlterField(
            model_name='alternativa',
            name='texto',
            field=models.CharField(max_length=100, verbose_name='Alternativa para a pergunta. Ex.: Feminino, Masculino'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='categoria', to='repadel.categoriapergunta', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='obrigatoria',
            field=models.BooleanField(default=True, verbose_name='Obrigatória?'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='texto',
            field=models.CharField(max_length=255, verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Resposta Aberta (texto)'), ('numerica', 'Resposta Numérica'), ('multipla', 'Múltipla Escolha')], default='multipla', max_length=20, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do questionário/enquete')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash')),
                ('perguntas', models.ManyToManyField(related_name='perguntas', to='repadel.pergunta', verbose_name='Selecione as perguntas para o questionário')),
            ],
            options={
                'verbose_name': 'questionário',
                'verbose_name_plural': 'questionários',
                'ordering': ['titulo'],
                'unique_together': {('titulo',)},
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_texto', models.TextField(blank=True, null=True, verbose_name='Texto da resposta')),
                ('respondido_em', models.DateTimeField(auto_now_add=True)),
                ('alternativa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alternativa', to='repadel.alternativa')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pergunta_resposta', to='repadel.pergunta')),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='questionario', to='repadel.questionario')),
                ('respondente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='respondente', to=settings.AUTH_USER_MODEL, verbose_name='Atleta')),
            ],
            options={
                'verbose_name': 'resposta',
                'verbose_name_plural': 'respostas',
                'ordering': ['questionario', 'pergunta'],
                'unique_together': {('questionario', 'pergunta')},
            },
        ),
    ]
