# Generated by Django 4.2.22 on 2025-08-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repadel', '0005_alter_alternativa_codigo_alter_alternativa_pergunta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='tipo',
            field=models.CharField(choices=[('TEXTO', 'Resposta Aberta (texto)'), ('NUMERICA', 'Resposta Numérica'), ('MULTIPLA_ESCOLHA', 'Múltipla Escolha')], default='MULTIPLA_ESCOLHA', max_length=20, verbose_name='Tipo'),
        ),
    ]
