# Generated by Django 4.2.22 on 2025-08-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repadel', '0006_alter_pergunta_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionario',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Se ativo, pode ser utilizado.', verbose_name='Ativo'),
        ),
    ]
