# Generated by Django 4.2.22 on 2025-11-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repadel', '0007_questionario_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='texto_exibido',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto exibido'),
        ),
    ]
