# Generated by Django 4.2.22 on 2025-11-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repadel', '0008_pergunta_texto_exibido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='ordem',
            field=models.PositiveIntegerField(null=True, verbose_name='Ordem'),
        ),
    ]
