# Generated by Django 4.2.22 on 2025-11-17 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repadel', '0009_pergunta_ordem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pergunta',
            options={'ordering': ['-is_active', 'categoria', 'ordem'], 'verbose_name': 'pergunta', 'verbose_name_plural': 'perguntas'},
        ),
    ]
