# Generated by Django 4.2.22 on 2025-11-17 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repadel', '0010_alter_pergunta_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriapergunta',
            options={'ordering': ['-is_active', 'ordem']},
        ),
        migrations.AddField(
            model_name='categoriapergunta',
            name='ordem',
            field=models.PositiveIntegerField(null=True, verbose_name='Ordem'),
        ),
    ]
